services:
  db:
    image: postgres:17
    container_name: "bank_db"
    restart: always
    environment:
      POSTGRES_DB: "bank"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin1111"
    ports:
      - "5432:5432"
    volumes:
      - bank-data:/home/dimoch1c/Projects/DbProjects/postgresql/data

volumes:
  bank-data: