server:
  port: 8080
  servlet:
    application-display-name: bank-backend

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: "rqqRu8tVBiu10PnfwECoBlvqMMqBJU4R5rVANbPsBaF"
  accessTokenExp: 600000
  refreshTokenExp: 604800000