server:
  port: 8080
  servlet:
    application-display-name: bank-backend

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: admin
    password: admin1111
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  secret: "rqqRu8tVBiu10PnfwECoBlvqMMqBJU4R5rVANbPsBaF"
  accessTokenExp: 600000
  refreshTokenExp: 604800000